# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 1000

# prompt
[character]
success_symbol = "[‚ùØ](bold green)"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

